### ISSUE TITLE
fatal Bug in notes-from-instructor

### ISSUE THREAD

**Issue by danverde** [byuitechops/notes-from-instructor#4]
```
C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\notes-from-instructor\main.js:95
                weekNum = titleArray[index + 1].replace(/\D+/g, '');
                                                ^

TypeError: Cannot read property 'replace' of undefined
    at titleArray.forEach (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\notes-from-instructor\main.js:95:49)
    at Array.forEach (<anonymous>)
    at makeDiscussion (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\notes-from-instructor\main.js:92:20)
    at nextTask (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5310:14)
    at next (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:5317:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:958:16
    at canvas.get (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\notes-from-instructor\main.js:63:21)
    at paginate (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:36:13)
    at Object.callReturned [as callback] (C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\canvas-wrapper\canvas.js:212:9)
    at C:\Users\Danverde\Documents\CONVERSION\d2l-to-canvas-conversion-tool\node_modules\async\dist\async.js:2257:31
```

**Comment by zachintosh** [comment]
I don't know if we're using this child module any more, but we haven't had the error either.
